name: "Ata's SSG HTML Builder"
description: "GitHub Action that builds HTML from PHP files in a repository based on github.com/atas/ssg"
runs:
  using: "composite"
  steps:
    - run: echo inputs.less_file_path is ${{ inputs.less_file_path }}
      shell: bash
    - run: echo INPUT_LESS_FILE_PATH is $INPUT_LESS_FILE_PATH
      shell: bash
    - run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
    - run: generate-html.sh
      shell: bash
inputs:
  less_file_path:
    description: "Path to the .less file to compile it, if you are using less."
    required: false
